-- MySQL Script generated by MySQL Workbench
-- Sun Jun 29 01:18:31 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema superstore_sales_data
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema superstore_sales_data
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `superstore_sales_data` DEFAULT CHARACTER SET utf8 ;
USE `superstore_sales_data` ;

-- -----------------------------------------------------
-- Table `superstore_sales_data`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `superstore_sales_data`.`customers` (
  `customer_id` VARCHAR(45) NOT NULL,
  `customer_name` VARCHAR(45) NULL,
  `segment` VARCHAR(45) NULL,
  `country` VARCHAR(25) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `region` VARCHAR(45) NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `superstore_sales_data`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `superstore_sales_data`.`orders` (
  `order_id` VARCHAR(45) NOT NULL,
  `orderDate` DATE NULL,
  `Ship_Date` DATE NULL,
  `ship_mode` VARCHAR(45) NULL,
  PRIMARY KEY (`order_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `superstore_sales_data`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `superstore_sales_data`.`products` (
  `product_id` VARCHAR(45) NOT NULL,
  `category` VARCHAR(20) NULL,
  `sub_category` VARCHAR(45) NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `superstore_sales_data`.`order_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `superstore_sales_data`.`order_details` (
  `row_id` INT NOT NULL,
  `order_id` VARCHAR(45) NOT NULL,
  `customer_id` VARCHAR(45) NOT NULL,
  `product_id` VARCHAR(45) NOT NULL,
  `sales` DECIMAL(10,2) NULL,
  PRIMARY KEY (`row_id`, `order_id`, `customer_id`, `product_id`),
  INDEX `order_id_idx` (`order_id` ASC),
  INDEX `product_id_idx` (`product_id` ASC) ,
  INDEX `customer_id_idx` (`customer_id` ASC) ,
  CONSTRAINT `order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `superstore_sales_data`.`orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `superstore_sales_data`.`customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `superstore_sales_data`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
